return {
    name = "curl",
    description = "Transfer data with URLs",
    homepage = "https://curl.se/",
    recipe_maintainers = { "tale" },
    default_license = "curl",
    upstream = {
        github = "curl/curl",
        repository_id = 569041,
        tag = "curl-{version}",
        separator = "_",
    },
    source = {
        url = "https://github.com/curl/curl/releases/download/{tag}/curl-{version}.tar.gz",
        archive = "tar.gz",
        strip_prefix = "curl-{version}",
        patches = {
            "--- a/CMake/curl-config.in.cmake\010+++ b/CMake/curl-config.in.cmake\010@@ -169 +169 @@\010-set(CURL_LIBRARIES_PRIVATE \"@LIBCURL_PC_LIBS_PRIVATE_LIST@\")\010+set(CURL_LIBRARIES_PRIVATE \"@CURL_LIBS@\")\010",
        },
    },
    build = {
        backend = "custom",
        dependencies = {
            "cmake@4.4.3",
            "pkgconf@3.0.7",
            "openssl@4.0.2",
            "zlib@1.3.2",
            "brotli@1.2.0",
            "zstd@1.5.7",
            "nghttp2@1.70.0",
            "nghttp3@1.18.0",
            "ngtcp2@1.25.0",
            "libidn2@2.3.8",
            "libpsl@0.23.3",
            "libssh2@1.11.1",
        },
        libraries = { "lib/libcurl.a" },
        steps = {
            configure = {
                {
                    "cmake",
                    "-S",
                    ".",
                    "-B",
                    "build",
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DCMAKE_INSTALL_PREFIX=/",
                    "-DCMAKE_POLICY_DEFAULT_CMP0193=NEW",
                    "-DCMAKE_INSTALL_LIBDIR=lib",
                    "-DCMAKE_INSTALL_INCLUDEDIR=include",
                    "-DCMAKE_INSTALL_BINDIR=bin",
                    "-DBUILD_SHARED_LIBS=OFF",
                    "-DBUILD_STATIC_LIBS=ON",
                    "-DBUILD_TESTING=ON",
                    "-DBUILD_STATIC_CURL=ON",
                    "-DCURL_USE_OPENSSL=ON",
                    "-DOPENSSL_ROOT_DIR={dependencies}",
                    "-DOPENSSL_USE_STATIC_LIBS=ON",
                    "-DCURL_USE_CMAKECONFIG=OFF",
                    "-DCURL_USE_PKGCONFIG=ON",
                    "-DPKG_CONFIG_ARGN=--static",
                    "-DCMAKE_PREFIX_PATH={dependencies}",
                    "-DCURL_ZLIB=ON",
                    "-DCURL_BROTLI=ON",
                    "-DCURL_ZSTD=ON",
                    "-DUSE_NGHTTP2=ON",
                    "-DUSE_NGTCP2=ON",
                    "-DUSE_LIBIDN2=ON",
                    "-DCURL_USE_LIBPSL=ON",
                    "-DCURL_USE_LIBSSH2=ON",
                    "-DCURL_DISABLE_LDAP=ON",
                    "-DCURL_DISABLE_LDAPS=ON",
                    "-DUSE_APPLE_SECTRUST=ON",
                    "-DCURL_CA_FALLBACK=ON",
                    "-DCURL_BUILD_EVERYTHING=ON",
                },
            },
            build = {
                { "cmake", "--build", "build", "--parallel", "{jobs}" },
            },
            check = {
                {
                    "/usr/bin/env",
                    "TFLAGS=-j{jobs}",
                    "cmake",
                    "--build",
                    "build",
                    "--target",
                    "test-nonflaky",
                    "--parallel",
                    "{jobs}",
                },
                {
                    "/bin/sh",
                    "-ec",
                    "features=$(build/src/curl --version); for feature in HTTP2 HTTP3 SSL brotli zstd IDN PSL sftp https; do case \"$features\" in *\"$feature\"*) ;; *) echo \"missing curl feature: $feature\" >&2; exit 1;; esac; done",
                },
            },
            install = {
                { "/usr/bin/env", "DESTDIR={prefix}", "cmake", "--install", "build" },
            },
        },
    },
    outputs = {
        bins = { "curl", "curl-config" },
        checks = {
            { "curl", "--version" },
            { "curl", "--help", "all" },
            { "curl", "--fail", "--silent", "file:///dev/null" },
            { "curl-config", "--version" },
        },
    },
    platforms = {
        ["aarch64-linux"] = {
            default_version = "8.22.0",
        },
        ["aarch64-macos"] = {
            default_version = "8.22.0",
        },
        ["x86_64-linux"] = {
            default_version = "8.22.0",
        },
    },
    versions = {
        ["8.22.0"] = {
            digests = {
                ["aarch64-linux"] = "d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1",
                ["aarch64-macos"] = "d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1",
                ["x86_64-linux"] = "d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1",
            },
            revision = 2,
        },
    },
}
