return {
    schema = 2,
    name = "curl",
    description = "Transfer data with URLs",
    default_version = "8.22.0",
    homepage = "https://curl.se/",
    systems = { "aarch64-macos", "aarch64-linux", "x86_64-linux" },
    build = {
        backend = "custom",
        dependencies = {
            "cmake@4.4.3",
            "pkgconf@3.0.7",
            "openssl@4.0.2",
            "zlib@1.3.2",
            "brotli@1.2.0",
            "zstd@1.5.7",
            "nghttp2@1.70.0",
            "libpsl@0.23.3",
            "libssh2@1.11.1",
        },
        steps = {
            configure = {
                {
                    "cmake",
                    "-S",
                    ".",
                    "-B",
                    "build",
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DCMAKE_INSTALL_PREFIX=/",
                    "-DCMAKE_INSTALL_LIBDIR=lib",
                    "-DBUILD_SHARED_LIBS=OFF",
                    "-DBUILD_STATIC_LIBS=ON",
                    "-DBUILD_TESTING=ON",
                    "-DBUILD_STATIC_CURL=ON",
                    "-DCURL_USE_OPENSSL=ON",
                    "-DOPENSSL_ROOT_DIR={dependencies}",
                    "-DOPENSSL_USE_STATIC_LIBS=ON",
                    "-DCURL_USE_CMAKECONFIG=OFF",
                    "-DCURL_USE_PKGCONFIG=ON",
                    "-DPKG_CONFIG_ARGN=--static",
                    "-DCMAKE_PREFIX_PATH={dependencies}",
                    "-DCURL_ZLIB=ON",
                    "-DCURL_BROTLI=ON",
                    "-DCURL_ZSTD=ON",
                    "-DUSE_NGHTTP2=ON",
                    "-DUSE_LIBIDN2=ON",
                    "-DCURL_USE_LIBPSL=ON",
                    "-DCURL_USE_LIBSSH2=ON",
                    "-DCURL_DISABLE_LDAP=ON",
                    "-DCURL_DISABLE_LDAPS=ON",
                    "-DUSE_APPLE_SECTRUST=ON",
                    "-DCURL_CA_FALLBACK=ON",
                    "-DCURL_BUILD_EVERYTHING=ON",
                },
            },
            build = {
                { "cmake", "--build", "build", "--parallel", "{jobs}" },
            },
            check = {
                {
                    "/usr/bin/env",
                    "TFLAGS=-j{jobs}",
                    "cmake",
                    "--build",
                    "build",
                    "--target",
                    "test-nonflaky",
                    "--parallel",
                    "{jobs}",
                },
                {
                    "/bin/sh",
                    "-ec",
                    'features=$(build/src/curl --version); for feature in HTTP2 SSL brotli zstd IDN PSL; do case "$features" in *"$feature"*) ;; *) echo "missing curl feature: $feature" >&2; exit 1;; esac; done',
                },
            },
            install = {
                { "/usr/bin/env", "DESTDIR={prefix}", "cmake", "--install", "build" },
            },
        },
    },
    inputs = {
        source = {
            url = "https://github.com/curl/curl/releases/download/curl-8_22_0/curl-{version}.tar.gz",
            archive = "tar.gz",
            strip_prefix = "curl-{version}",
        },
    },
    outputs = {
        libraries = { "lib/libcurl.a" },
        bins = { "curl", "curl-config" },
        checks = {
            { "curl", "--version" },
            { "curl", "--help", "all" },
            { "curl", "--fail", "--silent", "file:///dev/null" },
            { "curl-config", "--version" },
        },
    },
    versions = {
        ["8.22.0"] = {
            inputs = {
                source = {
                    sha256 = "d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1",
                },
            },
        },
    },
}
